stages:
  - environment_base
  - environment_variants
  - build_variants
  - unit_test
#  - integration_test
  - system_test

before_script:
  - docker info

base_ubuntu:
  stage: environment_base
  only:
    - schedules
  script:
    #- pwd
    #- export
    - cd $CI_PROJECT_DIR/_gitlab-ci/docker/base-ubuntu
    - docker rmi base_ubuntu:latest
    - docker build --no-cache -t base_ubuntu:latest --target base_ubuntu .
    
base_ubuntu_srsgui:
  stage: environment_base
  only:
    - schedules
  script:
    #- docker build -t $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}_base_ubuntu .
    - cd $CI_PROJECT_DIR/_gitlab-ci/docker/base-ubuntu
    - docker rmi base_ubuntu_srsgui:latest
    - docker build --no-cache -t base_ubuntu_srsgui:latest --target base_ubuntu_srsgui .

variant_minimal:
  stage: environment_variants
  only:
    - schedules
  script:
    - cd $CI_PROJECT_DIR/_gitlab-ci/docker/variants
    - docker rmi variant_minimal:latest
    - docker build --no-cache -t variant_minimal:latest .
    
variant_minimal_srslte_subproj:
  stage: environment_variants
  only:
    - schedules
  script:
    - cd $CI_PROJECT_DIR/_gitlab-ci/docker/variants
    - docker rmi variant_minimal_srslte_subproj:latest
    - docker build --no-cache -t variant_minimal_srslte_subproj:latest --build-arg INCLUDE_SRSLTE=false .

variant_cmnalib:
  stage: environment_variants
  only:
    - schedules
  script:
    - cd $CI_PROJECT_DIR/_gitlab-ci/docker/variants
    - docker rmi variant_cmnalib:latest
    - docker build --no-cache -t variant_cmnalib:latest --build-arg INCLUDE_CMNALIB=true .
    
variant_cmnalib_uhd:
  stage: environment_variants
  only:
    - schedules
  script:
    - cd $CI_PROJECT_DIR/_gitlab-ci/docker/variants
    - docker rmi variant_cmnalib_uhd:latest
    - docker build --no-cache -t variant_cmnalib_uhd:latest --build-arg INCLUDE_CMNALIB=true --build-arg INCLUDE_UHD=true .
    
variant_uhd:
  stage: environment_variants
  only:
    - schedules
  script:
    - cd $CI_PROJECT_DIR/_gitlab-ci/docker/variants
    - docker rmi variant_uhd:latest
    - docker build --no-cache -t variant_uhd:latest --build-arg INCLUDE_UHD=true .
    
variant_full:
  stage: environment_variants
  only:
    - schedules
  script:
    - cd $CI_PROJECT_DIR/_gitlab-ci/docker/variants
    - docker rmi variant_full:latest
    - docker build --no-cache -t variant_full:latest --build-arg INCLUDE_CMNALIB=true --build-arg INCLUDE_UHD=true --build-arg INCLUDE_LIMESDR=true .
    
#variant_noradio:
  #stage: environment_variants
  #script:
    #- cd $CI_PROJECT_DIR/_gitlab-ci/docker/variant-noradio
    #- docker build -t variant_noradio .
    
#variant_uhd:
  #stage: environment_variants
  #script:
    #- cd $CI_PROJECT_DIR/_gitlab-ci/docker/variant-uhd
    #- docker build -t variant_uhd .
    
#variant_allradio:
  #stage: environment_variants
  #script:
    #- cd $CI_PROJECT_DIR/_gitlab-ci/docker/variant-allradio
    #- docker build -t variant_allradio .
  
#build_environment_image:
  #stage: setup
  #script:
     #- cd _gitlab-ci
     #- docker build -t falcon-test .
    #- docker run -v `pwd`/.:/test -i falcon-test /test/testscripts/./test_all.sh /falcon/build /tmp
   #- echo "Tapa Tapa"
   #- docker run hello-world

sys_minimal:
  stage: system_test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - docker run --rm -v `pwd`/.:/falcon -v /tmp:/tmp/tmp-host -i variant_minimal:latest /falcon/_gitlab-ci/testscripts/./test_all.sh ~/falcon-build /tmp
    
sys_minimal_srslte_subproj:
  stage: system_test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - docker run --rm -v `pwd`/.:/falcon -v /tmp:/tmp/tmp-host -i variant_minimal_srslte_subproj:latest /falcon/_gitlab-ci/testscripts/./test_build.sh ~/falcon-build /tmp

sys_cmnalib:
  stage: system_test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - docker run --rm -v `pwd`/.:/falcon -i variant_cmnalib:latest /falcon/_gitlab-ci/testscripts/./test_all.sh ~/falcon-build /tmp
    
sys_cmnalib_uhd:
  stage: system_test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - docker run --rm -v `pwd`/.:/falcon -i variant_cmnalib_uhd:latest /falcon/_gitlab-ci/testscripts/./test_all.sh ~/falcon-build /tmp

sys_uhd:
  stage: system_test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - docker run --rm -v `pwd`/.:/falcon -i variant_uhd:latest /falcon/_gitlab-ci/testscripts/./test_all.sh ~/falcon-build /tmp
    
sys_full:
  stage: system_test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - docker run --rm -v `pwd`/.:/falcon -i variant_full:latest /falcon/_gitlab-ci/testscripts/./test_all.sh ~/falcon-build /tmp
